export const styles = {
  profileContainer: {
    marginTop: "50px",
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "20px",
    backgroundColor: "#f8f9fa",
    fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
  },
  profileHeader: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "30px",
    marginBottom: "20px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
  },
  profileInfo: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    marginBottom: "20px",
    flexWrap: "wrap",
  },
  profileImage: {
    width: "120px",
    height: "120px",
    borderRadius: "50%",
    objectFit: "cover",
    border: "4px solid #e9ecef",
  },
  profileDetails: {
    flex: 1,
    minWidth: "250px",
  },
  organizationName: {
    fontSize: "2rem",
    fontWeight: "bold",
    color: "#2c3e50",
    marginBottom: "8px",
  },
  userName: {
    fontSize: "1.8rem",
    fontWeight: "bold",
    color: "#2c3e50",
    marginBottom: "8px",
  },
  address: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: "#6c757d",
    marginBottom: "10px",
  },
  rating: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "1.1rem",
  },
  stars: {
    display: "flex",
    gap: "2px",
  },
  contactInfo: {
    display: "flex",
    gap: "20px",
    marginTop: "15px",
    flexWrap: "wrap",
  },
  contactItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: "#495057",
    fontSize: "0.9rem",
  },
  section: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "25px",
    marginBottom: "20px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
  },
  sectionTitle: {
    fontSize: "1.5rem",
    fontWeight: "bold",
    color: "#2c3e50",
    marginBottom: "20px",
    borderBottom: "2px solid #e9ecef",
    paddingBottom: "10px",
    display: "flex",
    alignItems: "center",
  },
  toursGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "20px",
  },
  tourCard: {
    border: "1px solid #e9ecef",
    borderRadius: "8px",
    padding: "0",
    transition: "transform 0.2s, box-shadow 0.2s",
    cursor: "pointer",
    backgroundColor: "#fafafa",
    overflow: "hidden",
    width:"60%"
  },
  tourImage: {
    width: "100%",
    height: "200px",
    objectFit: "cover",
    borderTopLeftRadius: "8px",
    borderTopRightRadius: "8px",
    transition: "transform 0.3s ease",
  },
  tourImageHover: {
    transform: "scale(1.05)",
  },
  tourContent: {
    padding: "20px",
  },
  tourCardHover: {
    transform: "translateY(-2px)",
    boxShadow: "0 4px 15px rgba(0,0,0,0.1)",
    backgroundColor: "#ffffff",
  },
  tourTitle: {
    fontSize: "1.2rem",
    fontWeight: "bold",
    color: "#2c3e50",
    marginBottom: "10px",
  },
  tourDetails: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    color: "#6c757d",
  },
  tourDetail: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "0.9rem",
  },
  tourPrice: {
    fontSize: "1.1rem",
    fontWeight: "bold",
    color: "#28a745",
    marginTop: "10px",
  },
  feedbackSection: {
    marginTop: "10px",
  },
  feedbackItem: {
    backgroundColor: "#f8f9fa",
    padding: "15px",
    borderRadius: "8px",
    marginBottom: "15px",
    border: "1px solid #e9ecef",
  },
  feedbackAuthor: {
    fontWeight: "bold",
    color: "#495057",
    marginBottom: "5px",
  },
  feedbackText: {
    color: "#6c757d",
    lineHeight: 1.5,
  },
  feedbackRating: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    marginTop: "8px",
  },
  feedbackForm: {
    backgroundColor: "#f0f8ff",
    padding: "20px",
    borderRadius: "8px",
    marginBottom: "20px",
    border: "2px solid #007bff",
  },
  formGroup: {
    marginBottom: "15px",
  },
  label: {
    display: "block",
    marginBottom: "5px",
    fontWeight: "bold",
    color: "#2c3e50",
  },
  input: {
    width: "100%",
    padding: "10px",
    borderRadius: "5px",
    border: "1px solid #ddd",
    fontSize: "14px",
    fontFamily: "inherit",
  },
  textarea: {
    width: "100%",
    padding: "10px",
    borderRadius: "5px",
    border: "1px solid #ddd",
    fontSize: "14px",
    fontFamily: "inherit",
    minHeight: "100px",
    resize: "vertical",
  },
  ratingSelector: {
    display: "flex",
    gap: "5px",
    marginTop: "5px",
  },
  ratingStarButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "2px",
  },
  formButtons: {
    display: "flex",
    gap: "10px",
    marginTop: "15px",
  },
  submitButton: {
    backgroundColor: "#28a745",
    color: "white",
    border: "none",
    padding: "10px 20px",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "bold",
  },
  cancelButton: {
    backgroundColor: "#6c757d",
    color: "white",
    border: "none",
    padding: "10px 20px",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "14px",
  },
  addFeedbackButton: {
    backgroundColor: "#007bff",
    color: "white",
    border: "none",
    padding: "12px 24px",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "bold",
    marginBottom: "20px",
  },
};