// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "LocaleSwitcher": {
    "label": "Change language EN ",
    "locale": "{locale, select, ru {Russian} en {English} other {Armenian}}"
  },
  "Home": {
    "label": "It’s Time To Explore The World",
    "destination": "Destination",
    "offer": "Offer",
    "tour": "Tour",
    "blog": "Blog",
    "locale": "{locale, select, ru {Russian} en {English} other {Armenian}}"
  },
  "CreateTour": {
    "destination": "Destination",
    "name": "Name",
    "startDate": "Start date",
    "description": "Description",
    "langEn": "English",
    "langHy": "Armenian",
    "langRu": "Russian",
    "priceAndRating": "Price and Rating",
    "price": "Price",
    "rating": "Rating",
    "tourCategory": "Tour Category",
    "status": "Status",
    "departureLocation": "Departure Location",
    "availableSeats": "Available Seats",
    "totalGroupSize": "Total Group Size",
    "accommodationType": "Accommodation Type",
    "star": "Star",
    "includedServices": "Included Services",
    "describeIncludedServices": "Describe included services",
    "images": "Images",
    "mainImage": "Main Image",
    "gallery": "Gallery",
    "select": "Select",
    "selectImage": "Select image",
    "selectImages": "Select images",
    "endDate": "End Date",
    "hotelStars": "Hotel Stars",
    "createNewTour": "Create New Tour",
    "fillInFields": "Fill in all required fields",
    "createTour": "Create Tour",
    "basicInformation": "Basic Information",
    "tourName": "Tour name",
    "carpool": "Carpool",
    "group": "Group",
    "package": "Package",
    "hotel": "Hotel",
    "hostel": "Hostel",
    "apartment": "Apartment",
    "villa": "Villa",
    "camping": "Camping",
    "active": "Active",
    "inactive": "Inactive",
    "draft": "Draft"
  },
  "LocaleLayout": {
    "title": "TWM"
  }
};
export default messages;